Reduce resources for some high-mem tools
usegalaxy-au/infrastructure pull request #952
Opened 2022-09-01 08:36 UTC by cat-bro

Reduce the cores/mem allocations for some high-mem tools to reduce congestion in the high-mem queues.  @Slugger70, @jlqfab what do you think?  We have sacct data but I'm not sure how to tell how efficient the allocations have been for the different tools.

```
halved:
flye: 120 -> 60
hifiasm: 120 -> 60
racon: 120 -> 60
medaka_consensus_pipeline: 120 -> 60
seqtk_seq: 120 -> 60
raven: 120 -> 60
hisat2: 60 -> 30
busco: 60 -> 30
spades tools: 60 -> 30

quartered:
minimap2: 120 -> 30

taken off high-mem altogether:
quast: 60 -> 16
```

2022-09-04 22:20 UTC, jlqfab commented
HI Catherine. I've looked at memory use data in sacct for the first 4 of these. There was no MaxRSS (max memory used) for any of these except hifiasm which showed (on pulsar-qld-high-mem0) usage of ~107.
We could drop memory assigned for all of some of these, and see how they go - sacct has a '--state OUT_OF_MEMORY' query that we could use to pick up which jobs are failing due to being out of memory.

2022-09-06 22:44 UTC, Slugger70 requested changes

2022-09-06 22:44 UTC, Slugger70 commented on files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
> +      cores: 60
Leave this one at 120 and 1922.

2022-09-06 22:44 UTC, Slugger70 commented on files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
> +      cores: 30
This is another heavily cpu bound tool (actually all of them are..) so we should do some investigation into their scaling (on a tool by tool basis) before we make these changes. Are they linear? Are they exponential? What is the point of diminishing returns?

2022-09-06 22:45 UTC, Slugger70 commented
We should look at all of the tools we send to high mem and investigate their scaling with resources and make sensible decisions based upon that rather than across the board reduction.

2022-09-19 01:18 UTC, closed without merging